### ISSUE TITLE
QuasiQuote de Bruijn benchmarks failed with 'Unrecognized Data' Error

### ISSUE THREAD

**Issue by lsrcz** [BillHallahan/G2#161] opened 2022-10-16 23:47 UTC
Hi! I am trying to reproduce the results in your G2Q paper, and I tried to run

```bash
cabal run QuasiQuote
```

The other three set of benchmarks worked smoothly, while the de Bruijn benchmark failed with the following out. Could you please help me check what was happening? I am using GHC 8.10.7.

```haskell
-- DeBruijn Eval -------
QuasiQuote: Unrecognized Data (DataCon (Name ":" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE))) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE))))))) with args [Type (TyCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) TYPE),App (App (App (App (Data (DataCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" (Just "GHC.Tuple") 0 Nothing) TYPE)) (TyForAll (NamedTyBndr (Id (Name "a" (Just "GHC.Tuple") 1 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" (Just "GHC.Tuple") 0 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" (Just "GHC.Tuple") 1 Nothing) TYPE)) (TyApp (TyApp (TyCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) (TyFun TYPE (TyFun TYPE TYPE))) (TyVar (Id (Name "a" (Just "GHC.Tuple") 0 Nothing) TYPE))) (TyVar (Id (Name "a" (Just "GHC.Tuple") 1 Nothing) TYPE))))))))) (Type (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) TYPE))) (Type (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))) (App (App (App (Data (DataCon (Name ":" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE))) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)))))))) (Type (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (App (Data (DataCon (Name "App" (Just "DeBruijn.Interpreter") 8214565720327906923 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 2))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 1)))))))) (App (Data (DataCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)))))) (Type (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (App (Data (DataCon (Name "App" (Just "DeBruijn.Interpreter") 8214565720327906923 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 2))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 1))))))),App (App (App (Data (DataCon (Name ":" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE))) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)))))))) (Type (TyCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) TYPE))) (App (App (App (App (Data (DataCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" (Just "GHC.Tuple") 0 Nothing) TYPE)) (TyForAll (NamedTyBndr (Id (Name "a" (Just "GHC.Tuple") 1 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" (Just "GHC.Tuple") 0 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" (Just "GHC.Tuple") 1 Nothing) TYPE)) (TyApp (TyApp (TyCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) (TyFun TYPE (TyFun TYPE TYPE))) (TyVar (Id (Name "a" (Just "GHC.Tuple") 0 Nothing) TYPE))) (TyVar (Id (Name "a" (Just "GHC.Tuple") 1 Nothing) TYPE))))))))) (Type (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) TYPE))) (Type (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))) (App (App (App (Data (DataCon (Name ":" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyFun (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE))) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)))))))) (Type (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (App (Data (DataCon (Name "App" (Just "DeBruijn.Interpreter") 8214565720327906923 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 2))))) (App (App (Data (DataCon (Name "App" (Just "DeBruijn.Interpreter") 8214565720327906923 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 2))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 1))))))))) (App (Data (DataCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)))))) (Type (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "Lam" (Just "DeBruijn.Interpreter") 8214565720327906922 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (App (Data (DataCon (Name "App" (Just "DeBruijn.Interpreter") 8214565720327906923 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 2))))) (App (App (Data (DataCon (Name "App" (Just "DeBruijn.Interpreter") 8214565720327906923 Nothing) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyFun (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 2))))) (App (Data (DataCon (Name "Var" (Just "DeBruijn.Interpreter") 8214565720327906921 Nothing) (TyFun (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE) (TyCon (Name "Expr" (Just "DeBruijn.Interpreter") 8214565720327906920 Nothing) TYPE)))) (App (Data (DataCon (Name "I#" (Just "GHC.Types") 8214565720327925190 Nothing) (TyFun TyLitInt (TyCon (Name "Int" (Just "GHC.Types") 8214565720327925189 Nothing) TYPE)))) (Lit (LitInt 1)))))))))) (App (Data (DataCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyForAll (NamedTyBndr (Id (Name "a" Nothing 0 Nothing) TYPE)) (TyApp (TyCon (Name "[]" (Just "GHC.Types") 0 Nothing) (TyFun TYPE TYPE)) (TyVar (Id (Name "a" Nothing 0 Nothing) TYPE)))))) (Type (TyCon (Name "(,)" (Just "GHC.Tuple") 0 Nothing) TYPE)))] in funcToSMT
CallStack (from HasCallStack):
  error, called at src/G2/Solver/Converters.hs:365:17 in g2-0.1.0.1-inplace:G2.Solver.Converters
```

**Comment by lsrcz** [comment] 2022-10-17 00:14
Update: also failed with GHC 8.2.2

**Comment by BillHallahan** [comment] 2022-10-18 16:11
Thanks for the report- it looks like something is going wrong with passing queries to the SMT solver.  I'll try and investigate this more deeply soon.

**Comment by BillHallahan** [comment] 2022-12-25 02:51
#172 fixes this error.  There appears to have been a bit of a regression in actually solving the DeBruijn tests, but they were always a struggle for G2Q.  Likely down to specific heuristics that have changed in the solver in the past several years.  I'm closing this as the error has been fixed, although I might mess with the heuristics a bit in the future.  Thanks for the report!

**Closed by BillHallahan** 2022-12-25 02:51 UTC
Labels: bug
